services:
  - type: web
    name: agridjangoportal
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn agrostudies_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: agridjangoportal.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: agridjangoportal-db
          property: connectionString

    postDeployCommand: python manage.py migrate   # Run migrations after deploy

databases:
  - name: agridjangoportal-db
    plan: free
    ipAllowList: []
