# Generated by Django 5.1.7 on 2025-03-26 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('country_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('shoes_size', models.CharField(blank=True, max_length=10, null=True)),
                ('shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('specialization', models.CharField(max_length=100)),
                ('secondary_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('smokes', models.CharField(choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], default='Never', max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('New', 'New'), ('Fixed', 'Fixed'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Quit', 'Quit')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='passports/')),
                ('terms_and_conditions', models.FileField(blank=True, null=True, upload_to='terms/')),
                ('health_statement_menora', models.FileField(blank=True, null=True, upload_to='health/')),
                ('health_statement_ayalon', models.FileField(blank=True, null=True, upload_to='health/')),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='medical/')),
                ('info_and_rights', models.FileField(blank=True, null=True, upload_to='info/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
            options={
                'unique_together': {('passport_number', 'university')},
            },
        ),
    ]
