# Generated by Django 4.2.20 on 2025-03-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='health_statement_ayalon',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='health_statement_menora',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='info_and_rights',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='medical_report',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='terms_and_conditions',
        ),
        migrations.AddField(
            model_name='candidate',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='good_moral',
            field=models.FileField(blank=True, null=True, upload_to='documents/moral/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='documents/nbi/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nc2_tesda',
            field=models.FileField(blank=True, null=True, upload_to='documents/tesda/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tor',
            field=models.FileField(blank=True, null=True, upload_to='documents/tor/'),
        ),
    ]
