# Generated by Django 4.2.20 on 2025-03-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_candidate_health_statement_ayalon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='year_graduated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
