# Generated by Django 4.2.20 on 2025-03-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_email_verified_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='additional_document',
            field=models.FileField(blank=True, null=True, upload_to='registration_documents/additional/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='registration_documents/cv/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='motivation_letter',
            field=models.FileField(blank=True, null=True, upload_to='registration_documents/motivation/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='registration_documents/recommendation/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='registration_documents/transcript/'),
        ),
    ]
