# Generated by Django 4.2.20 on 2025-03-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registration_additional_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='additional_document',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='cv_resume',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='motivation_letter',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='recommendation_letter',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='transcript',
        ),
        migrations.AddField(
            model_name='registration',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='good_moral',
            field=models.FileField(blank=True, null=True, upload_to='documents/moral/', verbose_name='Good Moral Character'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='documents/nbi/', verbose_name='NBI Clearance'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nc2_tesda',
            field=models.FileField(blank=True, null=True, upload_to='documents/tesda/', verbose_name='NC2 from TESDA'),
        ),
        migrations.AddField(
            model_name='registration',
            name='tor',
            field=models.FileField(blank=True, null=True, upload_to='documents/tor/', verbose_name='Transcript of Records (TOR)'),
        ),
    ]
