# Generated by Django 4.2.20 on 2025-03-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_registration_additional_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='core.agricultureprogram'),
        ),
        migrations.AddField(
            model_name='registration',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
