# Generated by Django 4.2.23 on 2025-08-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_candidate_program_registration_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agricultureprogram',
            name='end_date',
        ),
    ]
