# Generated by Django 4.2.23 on 2025-08-21 18:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_user_id_ae0b38_idx',
            old_name='core_activ_user_id_2a2fba_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_action__ba020b_idx',
            old_name='core_activ_action__8a6671_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_timesta_44c73d_idx',
            old_name='core_activ_timesta_7642d5_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='after_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='before_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
