# Generated by Django 4.2.23 on 2025-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_core_activ_user_id_2a2fba_idx_core_activi_user_id_ae0b38_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureprogram',
            name='required_gender',
            field=models.CharField(choices=[('Any', 'Any'), ('Male', 'Male Only'), ('Female', 'Female Only')], default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='agricultureprogram',
            name='requires_license',
            field=models.BooleanField(default=False, verbose_name="Requires International Driver's License"),
        ),
    ]
