# Generated by Django 4.2.23 on 2025-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agricultureprogram_required_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_international_license',
            field=models.BooleanField(default=False),
        ),
    ]
