# Generated by Django 4.2.23 on 2025-08-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_has_international_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license_scan',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
