# Generated by Django 4.2.25 on 2025-10-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_license_scan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agricultureprogram',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='agricultureprogram',
            name='image',
            field=models.ImageField(blank=True, help_text='Program/Farm image', null=True, upload_to='program_images/'),
        ),
        migrations.AddField(
            model_name='agricultureprogram',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display on landing page as featured program'),
        ),
    ]
