# Generated by Django 4.2.25 on 2025-10-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_program_image_and_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureprogram',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, help_text='Deadline for program registration. If not set, registration will be open until start date.'),
        ),
        migrations.AddField(
            model_name='agricultureprogram',
            name='country',
            field=models.CharField(max_length=100, default='', help_text='Country where the program is located'),
            preserve_default=False,
        ),
    ]