# Generated by Django 5.2.7 on 2025-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_candidate_is_complete_candidate_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_certificate',
            field=models.FileField(blank=True, null=True, upload_to='academic_certificates/', verbose_name='Academic Certificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field of Study'),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AddField(
            model_name='profile',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True, verbose_name='Highest Education Level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Issue Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='passport_scans/', verbose_name='Passport Scan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Issue'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Special Requirements'),
        ),
        migrations.AddField(
            model_name='profile',
            name='willing_to_relocate',
            field=models.BooleanField(default=True, verbose_name='Willing to Relocate'),
        ),
    ]
