# Generated by Django 5.2.7 on 2025-10-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_candidate_is_complete_remove_candidate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport Number'),
        ),
    ]
