# Generated by Django 5.2.7 on 2025-10-15 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_profile_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondary_specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary Specialization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Shirt Size'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shoes_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Shoes Size'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smokes',
            field=models.CharField(choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], default='Never', max_length=10, verbose_name='Smoking Habits'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Specialization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.university', verbose_name='University'),
        ),
    ]
