# Generated by Django 5.2.7 on 2025-10-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_program_deadline_and_country'),
        ('core', '0020_profile_secondary_specialization_profile_shirt_size_and_more'),
    ]

    operations = [
    ]
