# Generated by Django 4.2.25 on 2025-10-24 07:55

from django.db import migrations

def copy_location_to_country(apps, schema_editor):
    AgricultureProgram = apps.get_model('core', 'AgricultureProgram')
    for program in AgricultureProgram.objects.all():
        # Default to the location value if it's a country name, otherwise use a default
        if program.location in ['Israel', 'Japan', 'Australia', 'New Zealand']:
            program.country = program.location
        else:
            program.country = 'Israel'  # Default country
        program.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20251024_0750'),
    ]

    operations = [
        migrations.RunPython(copy_location_to_country),
    ]