# Generated by Django 5.2.7 on 2025-10-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_populate_program_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma/', verbose_name='Diploma'),
        ),
        migrations.AddField(
            model_name='profile',
            name='good_moral',
            field=models.FileField(blank=True, null=True, upload_to='documents/moral/', verbose_name='Good Moral Character'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='documents/nbi/', verbose_name='NBI Clearance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nc2_tesda',
            field=models.FileField(blank=True, null=True, upload_to='documents/tesda/', verbose_name='NC2 from TESDA'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tor',
            field=models.FileField(blank=True, null=True, upload_to='documents/tor/', verbose_name='Transcript of Records (TOR)'),
        ),
        migrations.AlterField(
            model_name='agricultureprogram',
            name='location',
            field=models.CharField(help_text='Specific location within the country', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
