# Generated by Django 5.2.7 on 2025-10-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_document_fields_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_graduated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Graduated'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Specialization'),
        ),
    ]
