# Generated by Django 5.2.7 on 2025-10-27 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('profile_image', 'Profile Image'), ('license_scan', 'License Scan'), ('passport_scan', 'Passport Scan'), ('academic_certificate', 'Academic Certificate'), ('tor', 'Transcript of Records (TOR)'), ('nc2_tesda', 'NC2 from TESDA'), ('diploma', 'Diploma'), ('good_moral', 'Good Moral Character'), ('nbi_clearance', 'NBI Clearance')], db_index=True, max_length=50)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the file in storage', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file content', max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(help_text='Model name: Profile, Registration, or Candidate', max_length=50)),
                ('model_id', models.PositiveIntegerField(help_text='ID of the model instance')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if file has been replaced or deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'document_type'], name='core_upload_user_id_cc256c_idx'), models.Index(fields=['user', 'file_hash'], name='core_upload_user_id_a859d0_idx'), models.Index(fields=['file_hash'], name='core_upload_file_ha_1df209_idx')],
                'unique_together': {('user', 'document_type', 'file_hash')},
            },
        ),
    ]
