# Generated by Django 5.2.7 on 2025-10-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_make_candidate_fields_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
    ]
