# Generated by Django 5.2.7 on 2025-10-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_allow_blank_names_in_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='academic_certificate',
            field=models.FileField(blank=True, null=True, upload_to='candidate_certificates/', verbose_name='Academic Certificate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='license_scan',
            field=models.FileField(blank=True, null=True, upload_to='candidate_licenses/', verbose_name='License Scan'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma/', verbose_name='Diploma'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='good_moral',
            field=models.FileField(blank=True, null=True, upload_to='documents/moral/', verbose_name='Good Moral Character'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='documents/nbi/', verbose_name='NBI Clearance'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nc2_tesda',
            field=models.FileField(blank=True, null=True, upload_to='documents/tesda/', verbose_name='NC2 from TESDA'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Passport Scan'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tor',
            field=models.FileField(blank=True, null=True, upload_to='documents/tor/', verbose_name='Transcript of Records (TOR)'),
        ),
    ]
