# Generated by Django 5.2.7 on 2025-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_missing_candidate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_id',
            field=models.CharField(blank=True, help_text='The unique ID from the OAuth provider', max_length=255, null=True, unique=True, verbose_name='OAuth Provider ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_picture_url',
            field=models.URLField(blank=True, help_text='Original profile picture URL from OAuth provider', null=True, verbose_name='OAuth Profile Picture URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('microsoft', 'Microsoft'), ('email', 'Email')], help_text='The social authentication provider used to create this account', max_length=20, null=True, verbose_name='OAuth Provider'),
        ),
    ]
