# Generated by Django 5.2.7 on 2025-12-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_profile_oauth_id_profile_oauth_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assigned_farm',
            field=models.CharField(blank=True, max_length=200, verbose_name='Assigned Farm Location'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='document_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for applicant to upload missing documents', null=True, verbose_name='Document Upload Deadline'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='farm_assignment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Farm Assignment Date'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='missing_documents_note',
            field=models.TextField(blank=True, help_text='List of missing documents or required fields', verbose_name='Missing Documents/Fields'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('New', 'New'), ('Missing_Docs', 'Missing Documents'), ('Validated', 'Validated - Ready for Farm Assignment'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
