# Generated by Django 5.2.7 on 2025-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_validation_deadline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_experience',
            field=models.TextField(blank=True, help_text='Describe your relevant work/job experience', null=True, verbose_name='Job Experience'),
        ),
    ]
