# Generated by Django 5.2.7 on 2025-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_job_experience_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureprogram',
            name='required_experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Minimum years of relevant job experience required. Set to 0 if no experience required.', verbose_name='Required Job Experience (Years)'),
        ),
    ]
