# Generated by Django 6.0.3 on 2026-03-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_required_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='health_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True, verbose_name='Health Condition'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='health_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Health Remarks'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Middle Initial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True, verbose_name='Health Condition'),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Health Remarks'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Middle Initial'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft (Saved)'), ('Missing_Docs', 'Missing Documents'), ('Validated', 'Validated - Ready for Farm Assignment'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
