# Generated by Django 6.0.3 on 2026-03-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_candidate_health_condition_candidate_health_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='institution_name',
        ),
    ]
