# Generated by Django 6.0.3 on 2026-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_profile_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='University'),
        ),
    ]
