# Generated by Django 6.0.3 on 2026-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_profile_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='University'),
        ),
    ]
