# Generated by Django 6.0.3 on 2026-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_candidate_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field of Study'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Highest Education Level'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Issue'),
        ),
    ]
