# Generated by Django 6.0.4 on 2026-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_candidate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_experience',
            field=models.TextField(blank=True, help_text='Describe your relevant work/job experience', null=True, verbose_name='Job Experience'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True, verbose_name='Highest Education Level'),
        ),
    ]
