# Generated by Django 6.0.4 on 2026-04-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_profile_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_experience',
        ),
    ]
