# Generated by Django 6.0.4 on 2026-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_profile_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_experience',
            field=models.TextField(blank=True, help_text='Describe your relevant work/job experience', null=True, verbose_name='Job Experience'),
        ),
    ]
